[package]
name = "rren"
version = "0.1.0"
authors = ["Bill Kudo <bluesky42624@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.21.0"
vulkano = "0.13"